### ISSUE TITLE
Allow to enable funnel

### ISSUE THREAD

**Issue by gbraad** [gbraad-homelab/private-forgejo#8]
https://github.com/gbraad-redhat/personal-forgejo/commit/8e9807d450242035a96b10466cce8532e6465a22

```yaml
      - name: Serve over funnel
        run: |
          podman exec forgejo tailscale funnel --bg 3000
```
